In [10]:
import pandas as pd
import numpy as np
print("pandas & numpy imported successfully")

pandas & numpy imported successfully

In [11]:
input_file = "Telco_Customer_Churn.xlsx"
df= pd.read_excel(input_file)
print(f"Dataset Shape: {df.shape[0]} rows and {df.shape[1]} columns")
df.head(3)

Dataset Shape: 7043 rows and 33 columns

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved

In [ ]:

df['Total Charges Clean'] = pd.to_numeric(df['Total Charges'], errors='coerce').fillna(0.0)


cols_to_drop = ['Count', 'Country', 'State']
df_cleaned = df.drop(columns=cols_to_drop)

print("Cleaned DataFrame columns count:", len(df_cleaned.columns))

Cleaned DataFrame columns count: 31

In [ ]:

def categorize_tenure(months):
    if months <= 12:
        return '0-1 Year'
    elif months <= 24:
        return '1-2 Years'
    elif months <= 48:
        return '2-4 Years'
    else:
        return '4+ Years'

df_cleaned['Tenure Cohort'] = df_cleaned['Tenure Months'].apply(categorize_tenure)


addon_services = ['Online Security', 'Online Backup', 'Device Protection', 
                  'Tech Support', 'Streaming TV', 'Streaming Movies']
df_cleaned['Addon Services Count'] = df_cleaned[addon_services].apply(
    lambda row: sum(row == 'Yes'), axis=1
)


df_cleaned['Avg Monthly Spend Check'] = np.where(
    df_cleaned['Tenure Months'] > 0,
    df_cleaned['Total Charges Clean'] / df_cleaned['Tenure Months'],
    df_cleaned['Monthly Charges']
)


output_file = "cleaned_telco_churn.csv"
df_cleaned.to_csv(output_file, index=False)

print("=" * 50)
print(f"PHASE 1 COMPLETE: Saved {df_cleaned.shape[0]} rows to '{output_file}'!")
print("=" * 50)
df_cleaned[['CustomerID', 'Tenure Months', 'Tenure Cohort', 'Addon Services Count', 'Total Charges Clean']].head()

==================================================
PHASE 1 COMPLETE: Saved 7043 rows to 'cleaned_telco_churn.csv'!
==================================================

,CustomerID,Tenure Months,Tenure Cohort,Addon Services Count,Total Charges Clean
0,3668-QPYBK,2,0-1 Year,2,108.15
1,9237-HQITU,2,0-1 Year,0,151.65
2,9305-CDSKC,8,0-1 Year,3,820.50
3,7892-POOKP,28,2-4 Years,4,3046.05
4,0280-XJGEX,49,4+ Years,4,5036.30